
# This is the project configuration file for your Supabase project.
project_id = "rldsrafveotztbnqgmot"

[functions.smart-recommendation]
verify_jwt = false

[functions.market-data-live]
verify_jwt = false
