// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rldsrafveotztbnqgmot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsZHNyYWZ2ZW90enRibnFnbW90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNjA4MDMsImV4cCI6MjA2MjgzNjgwM30.Cmse9yrEaXqN3lGOb-o2nU9UnbzkccKS-0MZcu9yYvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);